sudo: required
services:
  - docker

before_install:
  - docker build -t holsimx/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run holsimx/react-test npm run test -- --coverage

after_success:
  - docker build -t holsimx/multi-client ./client
  - docker build -t holsimx/multi-nginx ./nginx
  - docker build -t holsimx/multi-server ./server
  - docker build -t holsimx/multi-worker ./worker 

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push holsimx/multi-client
  - docker push holsimx/multi-nginx
  - docker push holsimx/multi-server
  - docker push holsimx/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-911534394243
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY